config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  # Authentication
  get '/auth/:provider/callback' => 'sessions#create', as: :omniauth_callback
  get '/signout' => 'sessions#destroy', as: :sign_out

  get 'activities/new_timer', as: :new_timer
  post 'activities/create_timer', as: :create_timer
  put 'activities/:id/status' => 'activities#update_status', as: :update_status
  resources :activities
  resources :projects
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  enum status: [:open, :close]
  enum track_type: [:timer, :manual]

  validates :start_time, :date_report, :status, :track_type, :user_id, presence: true

  belongs_to :user
  belongs_to :project

  validate :end_time_greater_than_start_time, on: [:create, :update]

  def calculate_total_time
    end_time - start_time
  end

  def show_start_time
    if self.timer?
      return start_time.localtime.strftime("%H:%M")
    else
      return start_time.strftime("%H:%M")
    end
  end

  def show_end_time
    if self.timer?
      return end_time.localtime.strftime("%H:%M")
    else
      return end_time.strftime("%H:%M")
    end
  end

  private

  def end_time_greater_than_start_time
    if start_time != nil && end_time != nil
      if start_time > end_time
        errors.add(:end_time, 'must be greater than the start time')
      end
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :user_id, presence: true

  belongs_to :user
  has_many :activities, dependent: :destroy

  def total_time_project
    activities.sum(:total_time)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, :nickname, :name, :token, :secret, presence: true

  has_many :activities
  has_many :projects
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :require_login
  before_action :find_activity, only: [:show, :edit, :update, :update_status, :destroy]

  def index
    @activities = Activity.all.order(date_report: :desc, created_at: :desc)
    @activities_by_day = @activities.group_by { |activity| activity.date_report }
  end

  def show
  end

  def new
    @activity = Activity.new
  end

  def new_timer
    @activity = Activity.new
  end

  def create_timer
    @activity = Activity.new(activity_attributes)
    @activity.user = current_user
    @activity.start_time = Time.now
    @activity.date_report = Date.today
    @activity.status = 'open'
    @activity.track_type = 'timer'
    if @activity.save
      redirect_to :activities, notice: 'Counting!'
    else
      render :new
    end
  end

  def create
    @activity = Activity.new(activity_attributes)
    @activity.user = current_user
    @activity.status = 'close'
    @activity.track_type = 'manual'
    if @activity.save
      @activity.update(total_time: @activity.calculate_total_time)
      redirect_to :activities, notice: 'Activity Saved!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @activity.assign_attributes(activity_attributes)
    if @activity.save
      flash[:success] = 'Activity Updated!'
      redirect_to activity_path(@activity)
    else
      render :edit
    end
  end

  def update_status
    if @activity.open?
      @activity.update(status: 'close', end_time: Time.now)
      @activity.update(total_time: @activity.calculate_total_time)
    else
      Activity.create(track_type: 'timer', status: 'open', name: @activity.name, start_time: Time.now, date_report: Date.today, user: current_user, project: @activity.project)
    end
    redirect_to :activities
  end

  def destroy
    @activity.destroy
    redirect_to :activities
  end

  private

  def activity_attributes
    params.require(:activity).permit(:name, :start_time, :end_time, :date_report, :project_id)
  end

  def find_activity
    @activity = Activity.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless current_user
      redirect_to :root, notice: 'You must be logged in.'
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_attributes)
    @project.user = current_user
    if @project.save
      redirect_to :activities, notice: 'Project Saved!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @project.assign_attributes(project_attributes)
    if @project.save
      flash[:success] = 'Project Updated!'
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to :activities
  end

  private

  def project_attributes
    params.require(:project).permit(:name)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    uid = auth_hash.uid
    nickname = auth_hash.info.nickname
    name = auth_hash.info.name
    token = auth_hash.credentials.token
    secret = auth_hash.credentials.secret
    user = User.find_or_initialize_by(uid: uid, nickname: nickname, name: name, token: token, secret: secret)
    if user.new_record? && !user.save
      redirect_to :root, notice: 'Oops, something went wrong. Try again.'
    else
      session[:user_id] = user.id
      redirect_to :activities, notice: 'Signed in!'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root, notice: 'Logged out!'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/activities/_add_project.html.erb
<%= f.label :project_id, 'Do you want to add a project?', class: 'control-label' %>
<%= f.collection_select :project_id, Project.all, :id, :name, { prompt: 'Project' }, class: 'form-control input-project' %>

app/views/activities/edit.html.erb
<% provide(:title, "Edit Activity") %>

<%= form_for @activity do |f| %>

  <%= render "shared/form_errors", model: @activity %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :name, 'Name', class: 'control-label' %>
        <%= f.text_field :name, placeholder: 'Update your activity name', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :project_id, 'Project', class: 'control-label' %>
        <%= f.collection_select :project_id, Project.all, :id, :name, { prompt: 'Project' }, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= label_tag :start_time, 'Start time', class: 'control-label' %>
        <%= text_field_tag :start_time, @activity.show_start_time, class: 'form-control time_select', readonly: true %>
      </div>
      <div class="form-group">
        <%= label_tag :end_time, 'End time', class: 'control-label' %>
        <% if @activity.open? %>
          <%= text_field_tag :end_time, "", class: 'form-control time_select', readonly: true %>
        <% else %>
          <%= text_field_tag :end_time, @activity.show_end_time, class: 'form-control time_select', readonly: true %>
        <% end %>
      </div>
      <div class="form-group">
        <%= label_tag :date_report, 'Report Date', class: 'control-label' %>
        <%= text_field_tag :date_report, @activity.date_report, class: 'form-control time_select', readonly: true %>
      </div>
    </div>
  </div>
  <br>
  <ul class="list-inline">
    <li><%= f.submit "Update", class: 'btn btn-primary' %></li>
    <li><%= link_to 'Back', :activities, class: 'btn btn-danger' %></li>
  </ul>
<% end %>

app/views/activities/index.html.erb
<% provide(:title, "Activities") %>
<%= link_to 'Add manually', :new_activity %>
<br><br>
<%= link_to 'Add timer', :new_timer %>
<hr>
<%= link_to 'Add project', :new_project %>
<hr>

<% if @activities.empty? %>
  <p>There's any activity yet.</p>
<% else %>
  <% @activities_by_day.each do |day, activities| %>
    <h2><%= day.strftime("%A, %d %h %Y") %></h2>
    <table class="table">
      <thead>
      </thead>
      <% for activity in activities %>
        <tbody>
          <tr>
            <td width="30%">
              <% if activity.name.empty? %>
                <%= link_to "no description", activity_path(activity) %>
              <% else %>
                <%= link_to activity.name, activity_path(activity) %>
              <% end %>
            </td>
            <td width="30%">
              <% if activity.project.nil? %>
                -
              <% else %>
                <%= link_to activity.project.name, project_path(activity.project) %>
              <% end %>
            </td>
            <td><%= Time.at(activity.total_time).utc.strftime("%H:%M:%S") if !activity.total_time.nil? %></td>
            <% if activity.open? %>
              <td><%= activity.show_start_time + " - Counting..." %></td>
              <td><%= link_to "Stop", update_status_path(activity), method: :put, class: 'btn btn-danger btn-xs' %></td>
            <% else %>
              <td><%= activity.show_start_time + " - " + activity.show_end_time %></td>
              <td><%= link_to "Continue", update_status_path(activity), method: :put, class: 'btn btn-danger btn-xs' %></td>
            <% end %>
          </tr>
        </tbody>
      <% end %>
    </table>
  <% end %>
<% end %>

app/views/activities/new.html.erb
<% provide(:title, "New Activity") %>

<%= form_for @activity do |f| %>

  <%= render "shared/form_errors", model: @activity %>

  <div class="form-inline">
  	<%= f.text_field :name, placeholder: 'What have you done?', class: 'form-control' %>
    <%= f.time_select :start_time, { ignore_date: true }, class: 'form-control time_select' %>
    -
    <%= f.time_select :end_time, { ignore_date: true }, class: 'form-control time_select' %>
    <%= f.date_field :date_report, value: Date.today, class: 'form-control' %>
  </div>
  <br>
  <%= render 'add_project', f: f %>
  <br><br>
  <ul class="list-inline">
    <li><%= f.submit "Save", class: 'btn btn-primary' %></li>
    <li><%= link_to 'Back', :activities, class: 'btn btn-danger' %></li>
  </ul>
<% end %>

app/views/activities/new_timer.html.erb
<%= form_for @activity, url: create_timer_path, method: 'post' do |f| %>

  <%= render "shared/form_errors", model: @activity %>

  <div class="form-inline">
  	<%= f.text_field :name, placeholder: 'What are you working on?', class: 'form-control' %>
  </div>
  <br>
  <%= render 'add_project', f: f %>
  <br><br>
  <ul class="list-inline">
    <li><%= f.submit "Go", class: 'btn btn-primary' %></li>
    <li><%= link_to 'Back', :activities, class: 'btn btn-danger' %></li>
  </ul>
<% end %>

app/views/activities/show.html.erb
<% provide(:title, "Activity Info") %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= label_tag :name, 'Name', class: 'control-label' %>
      <%= text_field_tag :name, @activity.name, class: 'form-control', readonly: true %>
    </div>
    <div class="form-group">
      <%= label_tag :project_id, 'Project', class: 'control-label' %>
      <% if !@activity.project.nil? %>
        <%= text_field_tag :project_id, @activity.project.name, class: 'form-control', readonly: true %>
      <% else %>
        <%= text_field_tag :project_id, "", class: 'form-control', readonly: true %>
      <% end %>
    </div>
    <div class="form-group">
      <%= label_tag :start_time, 'Start time', class: 'control-label' %>
      <%= text_field_tag :start_time, @activity.show_start_time, class: 'form-control time_select', readonly: true %>
    </div>
    <div class="form-group">
      <%= label_tag :end_time, 'End time', class: 'control-label' %>
      <% if @activity.open? %>
        <%= text_field_tag :end_time, "", class: 'form-control time_select', readonly: true %>
      <% else %>
        <%= text_field_tag :end_time, @activity.show_end_time, class: 'form-control time_select', readonly: true %>
      <% end %>
    </div>
    <div class="form-group">
      <%= label_tag :date_report, 'Report Date', class: 'control-label' %>
      <%= text_field_tag :date_report, @activity.date_report, class: 'form-control time_select', readonly: true %>
    </div>
  </div>
</div>
<br>
<ul class="list-inline">
  <li><%= link_to 'Edit', edit_activity_path(@activity), class: 'btn btn-primary' %></li>
  <li><%= link_to 'Eliminar', activity_path(@activity), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %></li>
  <li><%= link_to 'Back', :activities, class: 'btn btn-default' %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <title><%= yield(:title) %> | Track Time</title>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <% if logged_in? %>
              <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown"><%= current_user.nickname %><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li><a tabindex="-1" href="#"><%= link_to "Recent Activity", :activities %></a></li>
                  <li class="divider"></li>
                  <li><a tabindex="-1" href="#"><%= link_to "Sign out", :sign_out %></a></li>
                </ul>
              </li>
            <% else %>
              <li role="presentation"><%= link_to 'Sign in with Twitter', '/auth/twitter' %></li>
            <% end %>
          </ul>
        </nav>
        <h3 class="text-muted"><%= link_to 'Track Time', :root %></h3>
      </div>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

      <br><br>
      <footer>
        <p style="text-align: center">&copy; Angela <%= Time.now.year %></p>
      </footer>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <%= render "shared/form_errors", model: @project %>

  <div class="form-inline">
  	<%= f.text_field :name, placeholder: 'Name your Project', class: 'form-control' %>
  </div>
  <br>
  <ul class="list-inline">
    <li><%= f.submit "Save", class: 'btn btn-primary' %></li>
    <li><%= link_to 'Back', :activities, class: 'btn btn-danger' %></li>
  </ul>
<% end %>

app/views/projects/edit.html.erb
<% provide(:title, "Edit Projet") %>

<%= render 'form' %>

app/views/projects/index.html.erb
<% provide(:title, "Projects") %>

<table class="table">
  <thead>
    <th>Project Name</th>
    <th>Total Time</th>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= Time.at(project.total_time_project).utc.strftime("%H:%M:%S") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<ul class="list-inline">
  <li><%= link_to 'Back', :activities, class: 'btn btn-default' %></li>
</ul>

app/views/projects/new.html.erb
<% provide(:title, "New Project") %>

<%= render 'form' %>

app/views/projects/show.html.erb
<% provide(:title, "Project Info") %>
<%= link_to 'See all projects', :projects %>
<hr>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= label_tag :name, 'Name', class: 'control-label' %>
      <%= text_field_tag :name, @project.name, class: 'form-control', readonly: true %>
    </div>
    <div class="form-group">
      <%= label_tag :total_time_project, 'Total Time Project', class: 'control-label' %>
      <%= text_field_tag :total_time_project, Time.at(@project.total_time_project).utc.strftime("%H:%M:%S"), class: 'form-control', readonly: true %>
    </div>
  </div>
</div>
<br>
<ul class="list-inline">
  <li><%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary' %></li>
  <li><%= link_to 'Eliminar', project_path(@project), method: :delete, data: {confirm: "Are you sure? All your activities will be removed too."}, class: 'btn btn-danger' %></li>
  <li><%= link_to 'Back', :activities, class: 'btn btn-default' %></li>
</ul>

app/views/shared/_form_errors.html.erb
<% if model.errors.any? %>
  <div>
    <p class="alert alert-danger">
      <%= pluralize(model.errors.count, "error") %> al guardar:<br><br>
      <% model.errors.full_messages.each do |msg| %>
        <%= msg %><br>
      <% end %>
    </p>
  </div>
<% end %>

app/views/site/index.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron">
  <h1>Track Time</h1>
  <p class="lead">The ultimate timer. It's insanely simple</p>
</div>